summary-project/challenge/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myApp import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^myApp/', include('myApp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^special/', views.special, name='special')
]

summary-project/myApp/urls.py
from django.conf.urls import url
from myApp import views

app_name = 'myApp'

urlpatterns = [
    url(r'^players/$', views.players, name='players'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    ]

summary-project/summary-project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myApp import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^myApp/', include('myApp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^special/', views.special, name='special')
]

summary-project/myApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Player(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=264, unique=True)


    def __str__(self):
        return self.first_name + " " + self.last_name


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

summary-project/myApp/forms.py
from django import forms
from myApp.models import Player, UserProfileInfo
from django.contrib.auth.models import User


class NewPlayerForm(forms.ModelForm):
    class Meta():
        model = Player
        fields = "__all__"

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

summary-project/myApp/views.py
from django.shortcuts import render
from myApp.models import Player
from myApp.forms import NewPlayerForm, UserProfileInfoForm, UserForm
# Login functionality import
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    myDict = {
        "intro": "Welcome to the homepage!",
        "users": "Go to /players to see user list.",
    }
    return render(request, 'myApp/index.html', context=myDict)


def players(request):
    player_list = Player.objects.order_by('first_name')
    user_dict = {'users': player_list}
    return render(request, 'myApp/players.html', context=user_dict)


def register(request):
    player_form = NewPlayerForm()

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        player_form = NewPlayerForm(data=request.POST)

        if player_form.is_valid():
            player_form.save(commit=True)
            return index(request)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
            print("Error, the form is invalid!")

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, "myApp/register.html", {
        "player_form": player_form,
        "user_form": user_form,
        "profile_form": profile_form,
        "registered": registered
        })


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed.")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login details")
    else:
        return render(request, 'myApp/login.html', {})


@login_required
def special(request):
    return HttpResponse("You are logged in!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

summary-project/templates/myApp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    </head>
    <body>
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myApp:players' %}">Players</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myApp:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'myApp:user_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        {% block content %}
        {% endblock %}
    </body>
</html>

summary-project/templates/myApp/index.html
<!DOCTYPE html>
{% extends "myApp/base.html" %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>{{ intro }}</h1>
        <p>{{ users|upper }}</p>
        <p>{{ users|cut:"user" }}</p>
    </div>
</div>
{% endblock %}

summary-project/templates/myApp/login.html
<!DOCTYPE html>
{% extends 'myApp/base.html' %}
{% block content %}
    <div class="jumbotron">
        <h1>Please login:</h1>
        <form class="" action="{% url 'myApp:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" value="" placeholder="Username">
            <label for="password">Password:</label>
            <input type="password" name="password" value="">
            <input type="submit" name="" value="Login">
        </form>
    </div>
{% endblock %}

summary-project/templates/myApp/players.html
<!DOCTYPE html>
{% extends "myApp/base.html" %}

{% block content %}
    {% if users %}
    <ol>
        {% for person in users %}
        <li>User info</li>
            <ul>
                <li>First name: {{ person.first_name }}</li>
                <li>Last name: {{ person.last_name }}</li>
                <li>E-mail: {{ person.email }}</li>
            </ul>
        {% endfor %}
    </ol>
    {% endif %}
{% endblock %}

summary-project/templates/myApp/register.html
<!DOCTYPE html>
{% extends "myApp/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registration!</h1>
        {% else %}
            <h1>Register here</h1>
            <h3>Fill out the form:</h3>
            <form class="" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
        <h2>Please, sign up the new player here!</h1>
        <form class="" method="POST">
            {{ player_form.as_p }}
            {% csrf_token %}
            <input type="submit" name="" class="btn btn-primary" value="Submit">
        </form>
    </div>
</div>
{% endblock %}